#'@name get_pred
#'
#'@title Get prediction of your model
#'
#'@description From the fitted model, using this function to calculate with the test set or unknown data point, valid for vector calculate.
#'
#'@param model A dataframe with coefficient and dependent variables, generated by generate_linear_model function.
#'
#'@param new_X A dataframe of the test set or unkonwn data point you want to predict by the fitted model
#'
#'@return A vector of response variable value corresponding to each new data point.
#'@import stats
#'@examples
#'dataset = LinearModelGenerator::data
#'model <- generate_linear_model(Depression~Age+Sex+Fatalism,dataset)
#'new_X <- data.frame(Age = c(15, 29, 34), Sex = c(1, 0, 1), Fatalism = c(2, 0, 5))
#'get_pred(model,new_X)
#'
#'@export
#'
get_pred <- function(model,new_X){
  coefficient_table <- model$coefficients_table
  beta_matrix = coefficient_table$Estimate
  new_X = as.matrix(cbind(1,new_X))
  beta_matrix <- as.matrix(beta_matrix)
  Y <- new_X %*% beta_matrix
  return(Y)
}
