#'@name get_pred
#'
#'@title Get prediction of your model
#'
#'@description From the fitted model, using this function to calculate with the test set or unknown data point, valid for vector calculate.
#'
#'@param model A dataframe with coefficient and dependent variables, generated by generate_linear_model function.
#'
#'@param new_X A dataframe of the test set or unkonwn data point you want to predict by the fitted model
#'
#'@return A vector of response variable value corresponding to each new data point.
#'@import stats
#'@examples
#'new_X <- data.frame(X1 = c(1, 2, 3), X2 = c(4, 5, 6), X3 = c(7, 8, 9))
#'model <- data.frame(Coefficients = c(-1,1,2,3),Variable = c("Intercept", "X1", "X2", "X3"))
#'get_pred(model,new_X)
#'
#'@export
#'
get_pred <- function(model,new_X){
  new_X = as.matrix(cbind(1,new_X))
  beta_matrix <- as.matrix(model$Coefficients)
  Y <- new_X %*% beta_matrix
  return(Y)
}
